### PR TITLE
Correctly encode json body

### PR DESCRIPTION
**Pull request by EagleChen**
trigger ci, and see why the test fails

### CODE REVIEW

**Comment by EagleChen** [comment]
@siddontang 

It seems 'index' cannot be created correctly in CI environment.

You can check the [error log](https://travis-ci.org/siddontang/go-mysql-elasticsearch/jobs/278631950#L1457-L1458).

But the same command works in my local env ( docker image: docker.elastic.co/elasticsearch/elasticsearch:5.5.0)
```
curl -XPUT localhost:9200/ttt 
{"acknowledged":true,"shards_acknowledged":true}
```

**Comment by siddontang** [comment]
Yes, @EagleChen 

Maybe we should use special version in Travis CI? The test also works well in my local ES 5.5, ES 5.6, very strange.

**Comment by EagleChen** [comment]
@siddontang 

I think so.  Travis CI supports [specific version](https://docs.travis-ci.com/user/database-setup/#Installing-specific-versions-of-ElasticSearch).

Then it's under your full control. You can upgrade and test new version of ES whenever you want.

**Comment by siddontang** [comment]
@EagleChen 

Can you use 5.6 version to try it?

**Comment by EagleChen** [comment]
@siddontang 

I've already fixed it.

The root cause is that `json.Marshal(nil)` returns `"null"` which is a string.

You can merge this PR ( to test ci, I've already included all your commits).
Or close it and fix your own PR ( see [my commit](https://github.com/siddontang/go-mysql-elasticsearch/pull/139/commits/ea4eb94b8ef09992453781cba0c105c4d0f4635c) for details ).

**Comment by siddontang** [comment]
Thanks @EagleChen 

I will close this PR.
Can you send a PR to fix this issue separately?

**Pull request closed without merging**
