### PR TITLE
#205 fix

### LINKED ISSUE #205: mysql TIMESTAMP type support
```
time="2018-01-25T15:40:53+08:00" level=error msg="index index: thl_note, type: thl_note, id: 3705, status: 400, error: {\"type\":\"mapper_parsing_exception\",\"reason\":\"failed to parse [updated_at]\",\"caused_by\":{\"type\":\"illegal_argument_exception\",\"reason\":\"Invalid format: \\\"2018-01-24 02:44:01\\\" is malformed at \\\" 02:44:01\\\"\"}}"
```

### PR DESCRIPTION
**Pull request by M2shad0w**
#205 fix

### CODE REVIEW

**Comment by siddontang** [comment]
Hi @M2shad0w 

Can you tell me why do you have the malformed timestamp "02:44:01" in your data?

**Comment by M2shad0w** [comment]
the  data, ddl is following

**Comment by siddontang** [comment]
Hi @M2shad0w 

Can you add a test for the timestamp?

**Comment by qieangel2013** [comment]
解决了timestamp同步报错问题

**Pull request merged**
