### PR TITLE
add support of parse json field

### PR DESCRIPTION
**Pull request by WangXiangUSTC**
I sync a table from mysql 5.7 with json field,  if I insert a value like blow:
`
"info" : "{"name": "wx"}"
`
and will get :
`
"info" : "eyJuYW1lIjoid3gifQ=="
`
in the elasticsearch.
So I add the parse of json field.

### CODE REVIEW

**Comment by siddontang** [comment]
Thanks @WangXiangUSTC 
Could you add some tests for JSON type?

**Comment by WangXiangUSTC** [comment]
@siddontang  travis ci's mysql version need to upgrade to 5.7

**Comment by siddontang** [comment]
Hi @WangXiangUSTC 

Does Travis CI support 5.7 by default now? Maybe we can update the travis now.

**Comment by WangXiangUSTC** [comment]
@siddontang Travis CI doesn't support mysql 5.7 default, but we can update to 5.7 use script.

**Comment by siddontang** [comment]
Cool, @WangXiangUSTC

**Comment by SuperNoobTao** [comment]
@WangXiangUSTC  does it support json array?

**Pull request merged**
