### PR TITLE
update vendor

### PR DESCRIPTION
**Pull request by siddontang**

### CODE REVIEW

**Comment by siddontang** [comment]
Hi @EagleChen 

I find that we can't pass CI now, see https://travis-ci.org/siddontang/go-mysql-elasticsearch/jobs/278188321

But I have tested on my local computer with ES 5.5, ES 5.6, both work fine, so I have no idea what is wrong now. Can you help me?

**Comment by EagleChen** [comment]
@siddontang 

OK, I'll run some tests locally and see if I can find out what's wrong.

**Comment by EagleChen** [comment]
@siddontang 

it works on my computer... (es: 5.5.0)

Maybe the failure is related to travis CI environment. I'll try to figure it out later.

**Comment by siddontang** [comment]
Thank you @EagleChen 

Maybe we should use a special ES version in travis CI.

**Pull request merged**
