### PR TITLE
fields convert to lower case or camel case

### PR DESCRIPTION
**Pull request by perfectacle**
this feature supports mysql fields convert to lower case or camel case to elasticsearch

### CODE REVIEW

**Comment by siddontang** [comment]
I am confused that why do we need camel case style? Maybe the lower case styple is acceptable.

**Comment by perfectacle** [comment]
@siddontang I think some people want to save camel case...
or maybe many people want to save lower case.
what do you think...?

**Comment by siddontang** [comment]
In many C style programs, snake_case is preferred, in Rust, camelCase is not even allowed. If the user may have different clients which use different languages, how do we do?

I don't think we need to satisfy all the user want. IMO, using lower-case all the time is the good practice for MySQL.

**Comment by perfectacle** [comment]
I see, so I colse this and will re pull requset,

**Pull request closed without merging**
